### ISSUE TITLE
DEseq, DEseq2, SAMseq, Bayseq, limma (voom), edgeR and edgeR_robust and robust voom

### ISSUE THREAD

**Issue by Shicheng-Guo** [eonurk/RNA-seq-differential-analyses-guideline#1]
Check this paper: 

https://www.sciencedirect.com/science/article/pii/S0888754319305750

DEseq, DEseq2, SAMseq, Bayseq, limma (voom), edgeR and edgeR_robust and robust voom

**Comment by eonurk** [comment]
Thanks!
